[package]
name = "quiz"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.7"
serde = { version = "1.0", features = ["derive"] }
miette = { version = "5.7", features = ["fancy"] }
silicon = { version = "0.5", default-features = false, features = ["anyhow"] }
syntect = "5.0"
