[package]
name = "quiz"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5"
itertools = "0.10"
miette = { version = "5.7", features = ["fancy"] }
prettytable-rs = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
wca = { version = "0.1", git = "https://github.com/Barsik-sus/wTools.git", branch = "ca_dot_command_merged" }
lazy_format = "2.0"
silicon = { version = "0.5", default-features = false, features = ["anyhow"] }
syntect = "5.0"
serde-inline-default = "0.1"
