[package]
name = "quiz"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10"
miette = { version = "5.7", features = ["fancy"] }
wca = { version = "0.1.3", git = "https://github.com/Wandalen/wTools/", branch = "alpha" }
