[[questions]]
description = """
At the end of this function, Rust will call drop on which variables

```rust
fn main() {
  let s1 = String::from("a");
  let s2 = String::from("b");
  let s3 = s2;
}
```
"""
answer = "s1 and s3"
distractors = [
  "s1, s2, and s3",
  "s2 and s3",
  "s3"
]
tags = ["rust"]
