version = "Two"
use_small_heuristics = "Max"
merge_derives = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
format_strings = true
wrap_comments = true
format_code_in_doc_comments = true
