[package]
name = "stdx"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
lazy-regex = "3.0"
wca.workspace = true
itertools.workspace = true
lazy_format.workspace = true
miette.workspace = true

[dev-dependencies]
expect-test.workspace = true
